[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[font]
size = 12.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.offset]
x = 0
y = 0

# [schemes.tokyo-night.bright]
# black = "#444b6a"
# blue = "#7da6ff"
# cyan = "#0db9d7"
# green = "#b9f27c"
# magenta = "#bb9af7"
# red = "#ff7a93"
# white = "#acb0d0"
# yellow = "#ff9e64"

# [schemes.tokyo-night.normal]
# black = "#32344a"
# blue = "#7aa2f7"
# cyan = "#449dab"
# green = "#9ece6a"
# magenta = "#ad8ee6"
# red = "#f7768e"
# white = "#787c99"
# yellow = "#e0af68"

# [schemes.tokyo-night.primary]
# background = "#1a1b26"
# foreground = "#a9b1d6"

# [schemes.tokyo-night-storm.bright]
# black = "#444b6a"
# blue = "#7da6ff"
# cyan = "#0db9d7"
# green = "#b9f27c"
# magenta = "#bb9af7"
# red = "#ff7a93"
# white = "#acb0d0"
# yellow = "#ff9e64"

# [schemes.tokyo-night-storm.normal]
# black = "#32344a"
# blue = "#7aa2f7"
# cyan = "#449dab"
# green = "#9ece6a"
# magenta = "#ad8ee6"
# red = "#f7768e"
# white = "#9699a8"
# yellow = "#e0af68"

# [schemes.tokyo-night-storm.primary]
# background = "#24283b"
# foreground = "#a9b1d6"

[scrolling]
history = 0
multiplier = 3

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.85
startup_mode = "Windowed"

[window.padding]
x = 0
y = 0
