scan_timeout = 100

format = """
[░▒▓](#a3aed2)\
$sudo\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$python\
$nodejs\
$rust\
$golang\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
$direnv\
\n$character"""

right_format="""
$status
"""

[status]
symbol = "󰅖 "
not_executable_symbol = "󱏎 "
not_found_symbol = "󰡯 "
sigint_symbol = " "
signal_symbol = "󱐋 "
disabled = false

[sudo]
style = "bg:#a3aed2 fg:#090c0c"
symbol = ""
format = "[ $symbol ]($style)"
disabled = false

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)[$read_only]($style)"
read_only = "󰉐"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[python]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol (${version})( \($virtualenv\)) ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[direnv]
symbol = " "
style = "fg:#a0a9cb"
disabled = false
loaded_msg = ""
unloaded_msg = "󰅖"
denied_msg = "󰦝"
allowed_msg = "󰕥"
not_allowed_msg = "󰦝"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
